permissions:
  id-token: write
  contents: read

jobs:

  security:
    name: Security Scan
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3

      - name: Terraform Format
        run: terraform fmt -check -recursive

      - name: Terraform Init
        run: terraform init -backend=false
        working-directory: infra/dev

      - name: Terraform Validate
        run: terraform validate
        working-directory: infra/dev


  terraform-plan:
    name: Terraform Plan
    runs-on: ubuntu-latest
    needs: security

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3

      - name: Azure Login
        uses: azure/login@v2
        with:
          client-id: 5099de5e-5d3c-446b-8f0e-e1a0cc92eba6
          tenant-id: 2fff2da8-8225-4289-a099-a7007fbcaf77
          subscription-id: 13dfd1e6-6770-4299-b7ea-6aa09b346468

      - name: Check Azure Login
        run: az account show

      - name: Terraform Init
        run: terraform init
        working-directory: infra/dev

      - name: Terraform Plan
        run: terraform plan
        working-directory: infra/dev